/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_symbian_tools_eclipseqt_qwebview_SWTQWebView */

#ifndef _Included_org_symbian_tools_eclipseqt_qwebview_SWTQWebView
#define _Included_org_symbian_tools_eclipseqt_qwebview_SWTQWebView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_symbian_tools_eclipseqt_qwebview_SWTQWebView
 * Method:    qt_back
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_symbian_tools_eclipseqt_qwebview_SWTQWebView_qt_1back
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_symbian_tools_eclipseqt_qwebview_SWTQWebView
 * Method:    qt_canGoBack
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_symbian_tools_eclipseqt_qwebview_SWTQWebView_qt_1canGoBack
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_symbian_tools_eclipseqt_qwebview_SWTQWebView
 * Method:    qt_canGoForward
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_symbian_tools_eclipseqt_qwebview_SWTQWebView_qt_1canGoForward
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_symbian_tools_eclipseqt_qwebview_SWTQWebView
 * Method:    qt_createWebView
 * Signature: (ILorg/symbian/tools/eclipseqt/qwebview/BrowserDelegate;)I
 */
JNIEXPORT jint JNICALL Java_org_symbian_tools_eclipseqt_qwebview_SWTQWebView_qt_1createWebView
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_symbian_tools_eclipseqt_qwebview_SWTQWebView
 * Method:    qt_forward
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_symbian_tools_eclipseqt_qwebview_SWTQWebView_qt_1forward
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_symbian_tools_eclipseqt_qwebview_SWTQWebView
 * Method:    qt_refresh
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_symbian_tools_eclipseqt_qwebview_SWTQWebView_qt_1refresh
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_symbian_tools_eclipseqt_qwebview_SWTQWebView
 * Method:    qt_setIconsDbPath
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_symbian_tools_eclipseqt_qwebview_SWTQWebView_qt_1setIconsDbPath
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_symbian_tools_eclipseqt_qwebview_SWTQWebView
 * Method:    qt_setUrl
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_symbian_tools_eclipseqt_qwebview_SWTQWebView_qt_1setUrl
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_symbian_tools_eclipseqt_qwebview_SWTQWebView
 * Method:    qt_stop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_symbian_tools_eclipseqt_qwebview_SWTQWebView_qt_1stop
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_symbian_tools_eclipseqt_qwebview_SWTQWebView
 * Method:    qt_getIcon
 * Signature: (I[I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_symbian_tools_eclipseqt_qwebview_SWTQWebView_qt_1getIcon
  (JNIEnv *, jobject, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_symbian_tools_eclipseqt_qwebview_QtControlWrapper */

#ifndef _Included_org_symbian_tools_eclipseqt_qwebview_QtControlWrapper
#define _Included_org_symbian_tools_eclipseqt_qwebview_QtControlWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_symbian_tools_eclipseqt_qwebview_QtControlWrapper
 * Method:    qt_dispose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_symbian_tools_eclipseqt_qwebview_QtControlWrapper_qt_1dispose
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_symbian_tools_eclipseqt_qwebview_QtControlWrapper
 * Method:    qt_resize
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_org_symbian_tools_eclipseqt_qwebview_QtControlWrapper_qt_1resize
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_symbian_tools_eclipseqt_qwebview_WebInspector */

#ifndef _Included_org_symbian_tools_eclipseqt_qwebview_WebInspector
#define _Included_org_symbian_tools_eclipseqt_qwebview_WebInspector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_symbian_tools_eclipseqt_qwebview_WebInspector
 * Method:    qt_setBrowser
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_symbian_tools_eclipseqt_qwebview_WebInspector_qt_1setBrowser
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_symbian_tools_eclipseqt_qwebview_WebInspector
 * Method:    qt_createWebInspector
 * Signature: (ILorg/symbian/tools/eclipseqt/qwebview/QtDelegate;)I
 */
JNIEXPORT jint JNICALL Java_org_symbian_tools_eclipseqt_qwebview_WebInspector_qt_1createWebInspector
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
