/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_symbian_tools_eclipseqt_qwebview_SWTQWebView */

#ifndef _Included_org_symbian_tools_eclipseqt_qwebview_SWTQWebView
#define _Included_org_symbian_tools_eclipseqt_qwebview_SWTQWebView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_symbian_tools_eclipseqt_qwebview_SWTQWebView
 * Method:    qt_back
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_symbian_tools_eclipseqt_qwebview_SWTQWebView_qt_1back
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_symbian_tools_eclipseqt_qwebview_SWTQWebView
 * Method:    qt_canGoBack
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_symbian_tools_eclipseqt_qwebview_SWTQWebView_qt_1canGoBack
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_symbian_tools_eclipseqt_qwebview_SWTQWebView
 * Method:    qt_canGoForward
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_symbian_tools_eclipseqt_qwebview_SWTQWebView_qt_1canGoForward
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_symbian_tools_eclipseqt_qwebview_SWTQWebView
 * Method:    qt_createChild
 * Signature: (ILorg/symbian/tools/eclipseqt/qwebview/Delegate;)I
 */
JNIEXPORT jint JNICALL Java_org_symbian_tools_eclipseqt_qwebview_SWTQWebView_qt_1createChild
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_symbian_tools_eclipseqt_qwebview_SWTQWebView
 * Method:    qt_dispose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_symbian_tools_eclipseqt_qwebview_SWTQWebView_qt_1dispose
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_symbian_tools_eclipseqt_qwebview_SWTQWebView
 * Method:    qt_forward
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_symbian_tools_eclipseqt_qwebview_SWTQWebView_qt_1forward
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_symbian_tools_eclipseqt_qwebview_SWTQWebView
 * Method:    qt_refresh
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_symbian_tools_eclipseqt_qwebview_SWTQWebView_qt_1refresh
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_symbian_tools_eclipseqt_qwebview_SWTQWebView
 * Method:    qt_resize
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_org_symbian_tools_eclipseqt_qwebview_SWTQWebView_qt_1resize
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     org_symbian_tools_eclipseqt_qwebview_SWTQWebView
 * Method:    qt_setUrl
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_symbian_tools_eclipseqt_qwebview_SWTQWebView_qt_1setUrl
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_symbian_tools_eclipseqt_qwebview_SWTQWebView
 * Method:    qt_stop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_symbian_tools_eclipseqt_qwebview_SWTQWebView_qt_1stop
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
